### PR TITLE
Multiple bug fixes

### LINKED ISSUE #596: Issues propsing winter season
✔ All fixtures on or after start date
✔ All fixtures on or before end date
❌ Teams have both legs defined
⚠ Division One: Missing fixture for Lamb Clandown A vs Norton SC
⚠ Division One: Missing fixture for Lamb Clandown A vs Peasedown Posse
⚠ Division One: Missing fixture for Lamb Clandown A vs Riverside
⚠ Division One: Missing fixture for Lamb Clandown A vs The Star
⚠ Division One: Missing fixture for Lamb Clandown A vs Waldegrave A
⚠ Division One: Missing fixture for Norton SC vs Lamb Clandown A
⚠ Division One: Missing fixture for Peasedown Posse vs Lamb Clandown A
⚠ Division One: Missing fixture for Riverside vs Lamb Clandown A
⚠ Division One: Missing fixture for The Star vs Lamb Clandown A
⚠ Division One: Missing fixture for Waldegrave A vs Lamb Clandown A
⚠ Division Two: Missing fixture for Crossways A vs Lamb Clandown B
⚠ Division Two: Missing fixture for Crossways B vs Lamb Clandown B
⚠ Division Two: Missing fixture for Lamb Clandown B vs Crossways A
⚠ Division Two: Missing fixture for Lamb Clandown B vs Crossways B
⚠ Division Two: Missing fixture for Lamb Clandown B vs Lamb Paulton
⚠ Division Two: Missing fixture for Lamb Clandown B vs Mardons
⚠ Division Two: Missing fixture for Lamb Clandown B vs Paulton Rovers
⚠ Division Two: Missing fixture for Lamb Clandown B vs Welton Rovers
⚠ Division Two: Missing fixture for Lamb Paulton vs Lamb Clandown B
⚠ Division Two: Missing fixture for Mardons vs Lamb Clandown B
⚠ Division Two: Missing fixture for Paulton Rovers vs Lamb Clandown B
⚠ Division Two: Missing fixture for Welton Rovers vs Lamb Clandown B
✔ No more than 2 consecutive home or away fixtures
✔ Teams aren't configured to play against themselves
✔ Teams are not playing multiple fixtures on the same date
✔ Venues do not have multiple fixtures on the same date
✔ No more than 1 consecutive byes

### LINKED ISSUE #598: Cannot create fixtures when seasons overlap
No error reported, fixture simply not created.

E.g.
Superleague season overlaps with League division
Create tournament fixture for date where seasons overlap

### LINKED ISSUE #600: Tournament labels target incorrect inputs

### LINKED ISSUE #601: Best of 7 tournament sayg changes to best of 3
Screenshot_2023-09-09-20-38-18-86_40deb401b9ffe8e1df2f1cc5ba480b12

### LINKED ISSUE #603: Add clearer/easier means of correcting sayg scores

### LINKED ISSUE #606: Should not be able to record invalid sayg score via enter key press
It is possible to enter 200 as the score and press enter - which should not be permitted

### PR DESCRIPTION
**Pull request by laingsimon**
Resolves #596
Resolves #598
Resolves #600
Resolves #606
Resolves #601
Resolves #603

### CODE REVIEW

File: CourageScores/Services/Command/AddOrUpdateTournamentGameCommand.cs [hunk 1]
```diff
@@ -50,16 +50,16 @@ public class AddOrUpdateTournamentGameCommand : AddOrUpdateCommand<TournamentGam
 
     protected override async Task<ActionResult<TournamentGame>> ApplyUpdates(TournamentGame game, EditTournamentGameDto update, CancellationToken token)
     {
-        var latestSeason = await _seasonService.GetForDate(update.Date, token);
+        var season = await _seasonService.Get(update.SeasonId, token);
```
Comment (laingsimon) [inline CourageScores/Services/Command/AddOrUpdateTournamentGameCommand.cs:53]: Update tests

File: CourageScores/ClientApp/src/components/division_fixtures/sayg/ScoreAsYouGo.js [hunk 2]
```diff
@@ -50,7 +50,7 @@ export function ScoreAsYouGo({
             const currentLegIndex = (homeScore || 0) + (awayScore || 0);
             const currentLeg = data.legs[currentLegIndex];
 
-            const unbeatable = newHomeScore > (numberOfLegs / 2) || newAwayScore > (numberOfLegs > 2);
+            const unbeatable = newHomeScore > (numberOfLegs / 2) || newAwayScore > (numberOfLegs / 2);
```
Comment (laingsimon) [inline CourageScores/ClientApp/src/components/division_fixtures/sayg/ScoreAsYouGo.js:53]: Update tests

File: CourageScores/ClientApp/src/components/division_fixtures/sayg/PlayerInput.js [hunk 3]
```diff
@@ -29,9 +29,26 @@ export function PlayerInput({
 
     async function keyUp(event) {
         if (event.key === 'Enter') {
-            /* istanbul ignore next */
-            await addThrow(score, 3, true);
-            /* istanbul ignore next */
+            if (savingInput) {
```
Comment (laingsimon) [inline CourageScores/ClientApp/src/components/division_fixtures/sayg/PlayerInput.js:32]: Update tests
